### ISSUE TITLE
populate phi.mat based on age and migration

### ISSUE THREAD

**Issue by steffenoppel** [ebuechley/EV.TV.Survival.Study#1]
The survival model pulls the respective parameter for monthly survival out of a matrix called 'phi.mat'. We need to create that matrix manually, or writing some code that does it automatically. For each individual, the matrix contains values which survival parameter defines survival from one month to the next, i.e. it should be 1 for a juvenile on migration, then 2 for the same juvenile in winter, then 3 until the immature starts migrating, when survival becomes 4 (and so on). For adults, survival would start at 5 or 7 and switch between 5,6, and 7 depending on the season.

If we also want to include captive/rehabilitated factors then we need more survival parameters and the matrix elements will then be corresponding numbers.

**Comment by steffenoppel** [comment]
I now included some code that does a reasonable job at this - what would be useful would be to specify age.at.deployment in MONTHS (i.e. a number!) rather than labels, because especially for immatures the transition to adult is otherwise difficult to code.

**Comment by ebuechley** [comment]
i will work on specifying age.at.deployment in months.

**Comment by ebuechley** [comment]
i have now specified date in months for all individuals for which we have an age at deployment. this is capped at 54 months (assuming a vulture is born in June and reaches it's 2nd year in January of the following year, then at 54 months it is Adult). There are still some birds for which we don't have an age, I have requested this info from data contributors. 

secondly, i have manually determined fates by visually inspecting plots of tracks, NSD, and fix rate. the "1b.Individual.based.summary.plots.R" script outputs these plots for each individual. there may be a better way to do this, which i will think about. let me know if suggestions. but, as of now, we have a fate for each individual. new data summary included on main page...
